build/install-build-tools.sh

Add pylint dependency for tests

---

build/install-build-tools.sh

Add some missing deps needed for unit testing

---

build/install-build-tools.sh

Provide a optional JAVA_MIRROR in case Oracle site has problems

---

build/install-build-tools.sh

Add pip modules for data-service tests

---

build/install-build-tools.sh

Update install-build-tools.sh with dependencies for platform-testing

---

build/build-pnda.sh
build/install-build-tools.sh

We also update the hostname in the /etc/hosts file, but for the
127.0.1.1 address. We do NOT erase the 127.0.0.1 localhost entry.
PNDA-2429

Gradle is not needed for gobblin, libaio1 is

---

build/install-build-tools.sh

Grunt is installed by npm, locally
PNDA-2441

Install grunt-cli globally instead of grunt

---

CHANGELOG.md
README.md
build/install-build-tools.sh
releases/release-note-3.4.md

Release 0.1.1

---

build/offline/create_mirror_deb.sh
build/offline/create_mirror_rpm.sh

For consistency use curl instead of wget in deb mirror script.
PNDA-2717

Replace wget with curl

---

build/offline/create_mirror_misc.sh
build/offline/create_mirror_python.sh
build/offline/pnda-logstash-plugin-dependencies.txt

Create mirror for logstash plugins

---

build/install-build-tools.sh

Support RHEL builds

---

CREATING_PNDA.md
README.md
build/offline/PYTHON_ADVANCED.md
build/offline/README.md

Add high level overview of creating PNDA

---

build/offline/requirements/pnda_requirements_py2.txt

Update version of boto

---

CHANGELOG.md
build/install-build-tools.sh

0.13.15 package has a bug, it required a invalid dependency.

Pin the version of SBT which is used to 0.13.13

---

build/offline/update_mirror_deb.sh
build/offline/update_mirror_python.sh
build/offline/update_mirror_rpm.sh

Scripts to update existing deb, rpm and python mirrors

---

CHANGELOG.md
mirror/create_mirror.sh
mirror/create_mirror_hdp.sh

Add HDP files to mirror

---

CHANGELOG.md
mirror/create_mirror_deb.sh
mirror/create_mirror_rpm.sh
mirror/dependencies/pnda-deb-package-dependencies.txt
mirror/dependencies/pnda-rpm-package-dependencies.txt

Add Ambari resources to mirror build

---

mirror/create_mirror.sh
mirror/create_mirror_anaconda.sh
mirror/create_mirror_deb.sh
mirror/create_mirror_misc.sh
mirror/create_mirror_python.sh
mirror/create_mirror_rpm.sh

Make mirror build fail fast

---

mirror/create_mirror_misc.sh
mirror/dependencies/pnda-static-file-dependencies.txt

Use logstash plugin manager now it is available

Create plugin pack for logstash

---

mirror/dependencies/pnda-rpm-package-dependencies.txt

Remove version from python-carbon rpm

---

mirror/dependencies/pnda_requirements_py3.txt

Added package support for sql magic to the build/mirror server.

PNDA-2832- Jupyter %sql magic support.

---

CHANGELOG.md
mirror/dependencies/pnda-rpm-package-dependencies.txt

Use redis 3.2.10 on redhat

---

CHANGELOG.md
CREATING_PNDA.md
PROXY.md
mirror/create_mirror_misc.sh
mirror/create_mirror_python.sh
set-proxy-env.sh

Add script to set a non-transparent proxy for the mirror build.

PNDA-3304: 

---

CHANGELOG.md
mirror/dependencies/pnda-deb-package-dependencies.txt

Include zip on deb mirror for HDP installation

---

mirror/create_mirror_deb.sh
mirror/dependencies/pnda-deb-package-dependencies.txt

Debian packages for Cloudera Manager 5.12

---

CHANGELOG.md
mirror/dependencies/pnda-deb-package-dependencies.txt
mirror/dependencies/pnda-rpm-package-dependencies.txt
mirror/dependencies/pnda_requirements_py2.txt
mirror/dependencies/pnda_requirements_py3.txt

Add mirror dependencies needed for PNDA-3238.

PNDA-3238: Add jupyter extensions to the kenel virtual environment.

---

mirror/create_mirror_anaconda.sh
mirror/create_mirror_cdh.sh
mirror/create_mirror_hdp.sh
mirror/create_mirror_misc.sh
mirror/dependencies/pnda-hdp-resources.txt

Added a retry when downloading some of the files with curl.
PNDA-3359

Add retry on some of the file downloads

---

CHANGELOG.md
mirror/create_mirror_deb.sh
mirror/create_mirror_hdp.sh
mirror/create_mirror_rpm.sh
mirror/dependencies/pnda-deb-package-dependencies.txt
mirror/dependencies/pnda-hdp-resources.txt
mirror/dependencies/pnda-rpm-package-dependencies-centos.txt
mirror/dependencies/pnda-rpm-package-dependencies-rhel.txt

Ambari version 2.6.0.0 and HDP version 2.6.3.0

---

CHANGELOG.md
mirror/dependencies/pnda-static-file-dependencies.txt

Zookeeper version 3.4.11

---

build/docs/ADVANCED.md

Fixed #147 by updating build doc

PNDA-1899: Scala Spark Jupyter Integration fixes

---

CHANGELOG.md
mirror/create_mirror_rpm.sh

Always import GPG keys

---

build/upstream-builds/build-gobblin.sh
mirror/create_mirror_deb.sh
mirror/create_mirror_hdp.sh
mirror/create_mirror_rpm.sh
mirror/dependencies/pnda-deb-package-dependencies.txt
mirror/dependencies/pnda-hdp-resources.txt
mirror/dependencies/pnda-rpm-package-dependencies-centos.txt
mirror/dependencies/pnda-rpm-package-dependencies-rhel.txt

Update Ambari to version 2.6.1.0 and HDP to version 2.6.4.0.
PNDA-4043

Ambari 2.6.1.0 and HDP 2.6.4.0 

---

mirror/common/utils.sh
mirror/create_mirror_anaconda.sh
mirror/create_mirror_cdh.sh
mirror/create_mirror_hdp.sh
mirror/create_mirror_misc.sh
mirror/dependencies/pnda-static-file-dependencies.txt

Factor out a function for robust curl operations

---

mirror/dependencies/pnda-static-file-dependencies.txt

adding consul as part of misc

---

mirror/create_mirror_misc.sh

Fixes issue with plugins not being available on new mirrors

Add missing move command
