pndaproject/pnda

build/install-build-tools.sh
Should we use the http://archive.cloudera.com/cdh5/cdh/5/spark-1.6.0-cdh5.9.0.tar.gz tarball instead ?
=> Update Spark version to 1.6.0

build/build-pnda.sh, build/docs/ADVANCED.md, build/upstream-builds/build-jupyterproxy.sh
This is required to cut dependency on online installation. Instead, we now handle this auxiliary application in the same way as we handle Kafka Manager.
PNDA-2691
=> Add jupyterproxy upstream project

build/offline/create_mirror.sh
PNDA-2691
Nodejs is at very old versions by default in the distros we use
=> Add specific mirror for nodejs

build/install-build-tools.sh
This enables the ability to build PNDA on the same node as the mirror is created, saving time/resources.
Previously, the build assumed a clean instance - which in the case of Ubuntu 14.04 means an old version of nodejs for which you need to install npm separately. This is no longer necessary in nodejs 6 and trying to force an install of npm fails if nodejs 6 (and therefore npm) is already installed.
=> Use npm in nodejs 6 for Ubuntu builds

mirror/tools/update_mirror_deb.sh
If the key is not exported and the key in the folder came from another machine, i.e. the mirror files were generated elsewhere, then the key used to sign the packages as part of the update operation will not match the one available for clients to download. For this reason, always export the key used when updating the mirror.
PNDA-3078
=> Always export GPG key to deb mirror folder in update_mirror_deb.sh

CHANGELOG.md, build/build-pnda.sh, build/install-build-tools.sh
Require manual download of JDK since oracle removed access to 8u74.
Disable gobblin tests as they often fail.
Disable console backend jsdoc generation
=> Build fixes for 0.1.1

build/install-build-tools.sh
This was previously floating to latest, which is now a problem for the kafka manager build which requires 0.13.x.
PNDA-3195
=> Specify fixed version of sbt for RHEL

mirror/dependencies/pnda-rpm-package-dependencies.txt
openssl 1.0.2 leaves ambari agents unable to connect to the server.
PNDA-3247
=> Fix openssl version at 1.0.1

mirror/create_mirror_misc.sh, mirror/dependencies/pnda-static-file-dependencies.txt
This resolves known issues with logstash-plugin install --local still trying to connect to Rubygems.
=> Uprev to logstash 5.2.2 and use prepare-offline-pack

build/upstream-builds/build-kafkatool.sh, build/upstream-builds/dependencies/upstream-kafka-tool-dependencies.txt
Problem Statement:
kafka-tool errored during offline installation
Analysis:
Kafkat-requires run time dependency gems which are, colored-1.2.gem, highline-1.7.8.gem, json-1.8.6.gem, retryable-1.3.6.gem, trollop-2.1.2.gem, zookeeper-1.4.11.gem, zk-1.9.6.gem
Change:
Created dependency file upstream-kafka-tool-dependencies.txt under build/upstream-builds/dependencies/
Added code in build-kafkatool.sh to wget the required gems using upstream-kafka-tool-dependencies.txt in the kafka-tool directory 
Test details:
Test1 -  created build based on develop branch and verified the gems, which all are available.
Test2 -  installation manually, using the kafkat.gem, by shutdown all the interfaces, so that, no reachability for internet using openstack instance web ui console.
Test3 -  offiline test in …
=> Adding dependency gems for kafka-tool for offline installation

mirror/create_mirror.sh
While mirrors exit early on problems, there's little consistency in the way
errors are reported by the underlying technologies. This ensures that 
there is at least one consistent message for ease of problem diagnosis.
=> Explicit ERROR on problem during creation

mirror/create_mirror_hdp.sh
5 (32 sec.) has appeared to be not sufficient on multiple occasions.
=> Increase retries for hdp to 9.

mirror/create_mirror.sh
To avoid returning the last comparison, which should under successful
circumstances
[[ 0 -ne 0 ]]
evaluate to 1,
an explicit exit 0 needs to be added at the end of the script.
=> Fix return code in 'create_mirror.sh'.

mirror/create_mirror_hdp.sh
It only retries on 'transient' errors and misses the
most common forms of failure
PNDA-3491
=> Don't use curl retry to retry

releases/release-note-3.6.md
PNDA release 3.6 online tested in openstack for the below mentioned tests, with the workaround for issue pndaproject/platform-salt#344.
TESTS:
Ubuntu-CDH - PICO - PASSED
Ubuntu-HDP - PICO - PASSED
Ubuntu-CDH - STD - PASSED
Ubuntu-HDP- STD - PASSED
RHEL-CDH - PICO - PASSED
RHEL-HDP - PICO - PASSED
RHEL-CDH - STD - PASSED
RHEL-HDP- STD - PASSED
=> Adding openstack test status

CHANGELOG.md, mirror/create_mirror_misc.sh, mirror/dependencies/pnda-deb-package-dependencies.txt, mirror/dependencies/pnda-rpm-package-dependencies-centos.txt, mirror/dependencies/pnda-rpm-package-dependencies-rhel.txt, mirror/dependencies/pnda_requirements_py2.txt, mirror/dependencies/pnda_requirements_py3.txt
PNDA-2832: Jupyter %sql magic support.
The Jupyter notebook should be able to support the sql-magic extension along with other extensions.
pnda - Added the sql-magic extension support related packages to the mirror repository.
platform-salt - Install the sql-magic extension support related packges to the kernel supporting virtual environments.
Verified the fix for AWS:
UBUNTU - PICO -CDH & HDP
UBUNTU - STD  -CDH & HDP
RHEL   - PICO -CDH & HDP
RHEL   - STD  -CDH & HDP
Verification pending for OpenStack
=> PNDA-2832: Jupyter %sql magic support.

CHANGELOG.md, build/build-pnda.sh, build/docs/ADVANCED.md, build/upstream-builds/build-gobblin.sh
PNDA-3133: Remove Gobblin fork and use release distribution instead.
Currently, gobblin is not a upstream project.
We need to build the gobblin components as upstream components except the pnda-gobblin modules .
- Changed the gobblin as a upsteam build project.
- Added the gobblin build script which builds gobblin as upstream project.
- Gobblin is built separately for CDH and HDP distibutions for below Hadoop Versions -
CDH - 2.6.0-cdh5.9.0
HDP - 2.7.3.2.6.3.0-235
Verified the fix for AWS:
UBUNTU - PICO -CDH & HDP
UBUNTU - STD -CDH & HDP
RHEL - PICO -CDH & HDP
RHEL - STD -CDH & HDP
Verification pending for OpenStack.
=> PNDA-3133: Remove Gobblin fork and use release distribution instead.

build/install-build-tools.sh
If JAVA_MIRROR environment variable is set, the specified mirror will be used.
Otherwise, will keep downloading from the hardcoded oracle URL.
=> Make install script use JAVA_MIRROR if defined

mirror/create_mirror.sh, mirror/create_mirror_apps.sh, mirror/dependencies/pnda_requirements_py2.txt
Understanding the Requirements:
PNDA-3128: Add kafka-python (new version) and avro python packages to app-packages.
Analysis
Currently kafka-python and avro-python egg files are not there in mirror. These egg files should be in /mirror_apps directory in mirror to stage into HDFS.
Solution
1. Created /mirror_apps directory in pnda mirror as this is the directory used in platform-salt/salt/app-packages/templates/sync.sh.tpl to stage the egg files into HDFS
2. Copied kafka-python and avro-python tar files from /mirror_python/packages into /mirror_apps directory
3. Built egg files for kafka-python and avro-python tar files.
File modified
pnda/mirror/create_mirror.sh
pnda/mirror/create_mirror_apps.sh
Testcase
UBUNTU : Created PNDA mirror and used this mirror to deploy the cluster
RHEL   : …
=> PNDA-3128: Add kafka-python new version and avro-python in app-packages

mirror/dependencies/pnda_requirements_py3.txt
=> fix missing matplotlib and dependencies of Jupyter python3 kernel
